# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Create env file
      run: |
        cd client
        touch .env
        cat << EOF >> .env
        ${{ secrets.ENV }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
       mongodbUrl: ${{secrets.mongodbUrl}}
       KAKAO_CLIENT_ID: ${{secrets.KAKAO_CLIENT_ID}}
       KAKAO_CLIENT_SECRET: ${{secrets.KAKAO_CLIENT_SECRET}}
       JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
       S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
       S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
       S3_REGION: ${{secrets.S3_REGION}}
       BUCKET_NAME: ${{secrets.BUCKET_NAME}}
       DOMAIN: ${{secrets.DOMAIN}}
       PORT: ${{secrets.PORT}}
       script: |
          sudo -s
          cd /home/ubuntu/main-project
          sudo git pull
          npm install
          sudo pm2 kill
          sudo pm2 start server.js
